skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
q3_26_core_staking = "G8LCc1EkmWZApyYgdYbiUGY6KCETY4q4KwAYo31y7822"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
